// src/lib/screenerUniverse.ts
//
// Frozen list of the 800 largest US-listed common stocks, ranked by market
// capitalisation. Twelve Data's /stocks catalog lists every US symbol but
// carries no market cap, sector or industry, so ranking a live universe would
// cost one /statistics credit per symbol on every rebuild — thousands per
// refresh against a 987/minute budget.
//
// This snapshot supplies the slow-moving descriptive fields (name, sector,
// industry, exchange). Everything that actually moves — price, change, volume,
// market cap, P/E, 52-week range, moving averages, performance — is fetched
// live from Twelve Data at request time.
//
// Snapshot taken 2026-09-10. Refresh occasionally so newly
// listed large caps appear; nothing breaks if it goes stale, the list just
// drifts from the true top 800.

/** [symbol, name, sector, industry, exchange] */
export type UniverseRow = readonly [string, string, string, string, string];

export const SCREENER_UNIVERSE: readonly UniverseRow[] = [
  ["NVDA","NVIDIA Corporation","Technology","Semiconductors","NASDAQ"],
  ["AAPL","Apple Inc.","Technology","Consumer Electronics","NASDAQ"],
  ["GOOG","Alphabet Inc.","Communication Services","Internet Content & Information","NASDAQ"],
  ["MSFT","Microsoft Corporation","Technology","Software - Infrastructure","NASDAQ"],
  ["AMZN","Amazon.com, Inc.","Consumer Cyclical","Specialty Retail","NASDAQ"],
  ["TSM","Taiwan Semiconductor Manufacturing Company Limited","Technology","Semiconductors","NYSE"],
  ["SPCX","Space Exploration Technologies Corp.","Industrials","Aerospace & Defense","NASDAQ"],
  ["AVGO","Broadcom Inc.","Technology","Semiconductors","NASDAQ"],
  ["META","Meta Platforms, Inc.","Communication Services","Internet Content & Information","NASDAQ"],
  ["TSLA","Tesla, Inc.","Consumer Cyclical","Auto - Manufacturers","NASDAQ"],
  ["SKHY","SK hynix Inc.","Technology","Semiconductors","NASDAQ"],
  ["MU","Micron Technology, Inc.","Technology","Semiconductors","NASDAQ"],
  ["LLY","Eli Lilly and Company","Healthcare","Drug Manufacturers - General","NYSE"],
  ["JPM","JPMorgan Chase & Co.","Financial Services","Banks - Diversified","NYSE"],
  ["WMT","Walmart Inc.","Consumer Defensive","Discount Stores","NASDAQ"],
  ["AMD","Advanced Micro Devices, Inc.","Technology","Semiconductors","NASDAQ"],
  ["V","Visa Inc.","Financial Services","Financial - Credit Services","NYSE"],
  ["XOM","Exxon Mobil Corporation","Energy","Oil & Gas Integrated","NYSE"],
  ["ASML","ASML Holding N.V.","Technology","Semiconductors","NASDAQ"],
  ["JNJ","Johnson & Johnson","Healthcare","Drug Manufacturers - General","NYSE"],
  ["INTC","Intel Corp.","Technology","Semiconductors","NASDAQ"],
  ["MA","Mastercard Incorporated","Financial Services","Financial - Credit Services","NYSE"],
  ["ABBV","AbbVie Inc.","Healthcare","Drug Manufacturers - General","NYSE"],
  ["BAC","Bank of America Corporation","Financial Services","Banks - Diversified","NYSE"],
  ["ORCL","Oracle Corporation","Technology","Software - Infrastructure","NYSE"],
  ["CVX","Chevron Corporation","Energy","Oil & Gas Integrated","NYSE"],
  ["CSCO","Cisco Systems, Inc.","Technology","Communication Equipment","NASDAQ"],
  ["COST","Costco Wholesale Corporation","Consumer Defensive","Discount Stores","NASDAQ"],
  ["PLTR","Palantir Technologies Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["KO","The Coca-Cola Company","Consumer Defensive","Beverages - Non-Alcoholic","NYSE"],
  ["LRCX","Lam Research Corporation","Technology","Semiconductors","NASDAQ"],
  ["CAT","Caterpillar Inc.","Industrials","Agricultural - Machinery","NYSE"],
  ["AMAT","Applied Materials, Inc.","Technology","Semiconductors","NASDAQ"],
  ["MRK","Merck & Co., Inc.","Healthcare","Drug Manufacturers - General","NYSE"],
  ["HSBC","HSBC Holdings plc","Financial Services","Banks - Diversified","NYSE"],
  ["UNH","UnitedHealth Group Incorporated","Healthcare","Medical - Healthcare Plans","NYSE"],
  ["PG","The Procter & Gamble Company","Consumer Defensive","Household & Personal Products","NYSE"],
  ["DELL","Dell Technologies Inc.","Technology","Computer Hardware","NYSE"],
  ["GE","GE Aerospace","Industrials","Aerospace & Defense","NYSE"],
  ["MS","Morgan Stanley","Financial Services","Financial - Capital Markets","NYSE"],
  ["NFLX","Netflix, Inc.","Communication Services","Entertainment","NASDAQ"],
  ["HD","The Home Depot, Inc.","Consumer Cyclical","Home Improvement","NYSE"],
  ["GS","The Goldman Sachs Group, Inc.","Financial Services","Financial - Capital Markets","NYSE"],
  ["PM","Philip Morris International Inc.","Consumer Defensive","Tobacco","NYSE"],
  ["RY","Royal Bank of Canada","Financial Services","Banks - Diversified","NYSE"],
  ["PANW","Palo Alto Networks, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["ARM","Arm Holdings plc American Depositary Shares","Technology","Semiconductors","NASDAQ"],
  ["WFC","Wells Fargo & Company","Financial Services","Banks - Diversified","NYSE"],
  ["SHEL","Shell plc","Energy","Oil & Gas Integrated","NYSE"],
  ["RTX","RTX Corporation","Industrials","Aerospace & Defense","NYSE"],
  ["MUFG","Mitsubishi UFJ Financial Group, Inc.","Financial Services","Banks - Diversified","NYSE"],
  ["NVS","Novartis AG","Healthcare","Drug Manufacturers - General","NYSE"],
  ["BABA","Alibaba Group Holding Limited","Consumer Cyclical","Specialty Retail","NYSE"],
  ["SNDK","Sandisk Corporation","Technology","Computer Hardware","NASDAQ"],
  ["AZN","AstraZeneca PLC","Healthcare","Drug Manufacturers - General","NYSE"],
  ["GEV","GE Vernova Inc.","Industrials","Industrial - Machinery","NYSE"],
  ["SAP","SAP SE","Technology","Software - Application","NYSE"],
  ["ANET","Arista Networks, Inc.","Technology","Computer Hardware","NYSE"],
  ["C","Citigroup Inc.","Financial Services","Banks - Diversified","NYSE"],
  ["TXN","Texas Instruments Incorporated","Technology","Semiconductors","NASDAQ"],
  ["KLAC","KLA Corporation","Technology","Semiconductors","NASDAQ"],
  ["TM","Toyota Motor Corporation","Consumer Cyclical","Auto - Manufacturers","NYSE"],
  ["TMO","Thermo Fisher Scientific Inc.","Healthcare","Medical - Diagnostics & Research","NYSE"],
  ["BHP","BHP Group Limited","Basic Materials","Industrial Materials","NYSE"],
  ["IBM","International Business Machines Corporation","Technology","Information Technology Services","NYSE"],
  ["AXP","American Express Company","Financial Services","Financial - Credit Services","NYSE"],
  ["SAN","Banco Santander, S.A.","Financial Services","Banks - Diversified","NYSE"],
  ["LIN","Linde plc","Basic Materials","Chemicals - Specialty","NASDAQ"],
  ["CRWD","CrowdStrike Holdings, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["VZ","Verizon Communications Inc.","Communication Services","Telecommunications Services","NYSE"],
  ["AMGN","Amgen Inc.","Healthcare","Drug Manufacturers - General","NASDAQ"],
  ["TTE","TotalEnergies SE","Energy","Oil & Gas Integrated","NYSE"],
  ["TD","The Toronto-Dominion Bank","Financial Services","Banks - Diversified","NYSE"],
  ["CRM","Salesforce, Inc.","Technology","Software - Application","NYSE"],
  ["MRVL","Marvell Technology, Inc.","Technology","Semiconductors","NASDAQ"],
  ["APH","Amphenol Corporation","Technology","Hardware, Equipment & Parts","NYSE"],
  ["NVO","Novo Nordisk A/S","Healthcare","Drug Manufacturers - General","NYSE"],
  ["STX","Seagate Technology Holdings plc","Technology","Computer Hardware","NASDAQ"],
  ["TMUS","T-Mobile US, Inc.","Communication Services","Telecommunications Services","NASDAQ"],
  ["PEP","PepsiCo, Inc.","Consumer Defensive","Beverages - Non-Alcoholic","NASDAQ"],
  ["SCHW","The Charles Schwab Corporation","Financial Services","Financial - Capital Markets","NYSE"],
  ["QCOM","QUALCOMM Incorporated","Technology","Semiconductors","NASDAQ"],
  ["DIS","The Walt Disney Company","Communication Services","Entertainment","NYSE"],
  ["DE","Deere & Company","Industrials","Agricultural - Machinery","NYSE"],
  ["MCD","McDonald's Corporation","Consumer Cyclical","Restaurants","NYSE"],
  ["GILD","Gilead Sciences, Inc.","Healthcare","Drug Manufacturers - General","NASDAQ"],
  ["ABT","Abbott Laboratories","Healthcare","Medical - Devices","NYSE"],
  ["UBS","UBS Group AG","Financial Services","Banks - Diversified","NYSE"],
  ["ADI","Analog Devices, Inc.","Technology","Semiconductors","NASDAQ"],
  ["T","AT&T Inc.","Communication Services","Telecommunications Services","NYSE"],
  ["NEE","NextEra Energy, Inc.","Utilities","Regulated Electric","NYSE"],
  ["WELL","Welltower Inc.","Real Estate","REIT - Healthcare Facilities","NYSE"],
  ["UNP","Union Pacific Corporation","Industrials","Railroads","NYSE"],
  ["COP","ConocoPhillips","Energy","Oil & Gas Exploration & Production","NYSE"],
  ["BLK","BlackRock, Inc.","Financial Services","Asset Management","NYSE"],
  ["SHOP","Shopify Inc.","Technology","Software - Application","NASDAQ"],
  ["SCCO","Southern Copper Corporation","Basic Materials","Copper","NYSE"],
  ["BA","The Boeing Company","Industrials","Aerospace & Defense","NYSE"],
  ["RIO","Rio Tinto Group","Basic Materials","Industrial Materials","NYSE"],
  ["BBVA","Banco Bilbao Vizcaya Argentaria, S.A.","Financial Services","Banks - Diversified","NYSE"],
  ["WDC","Western Digital Corporation","Technology","Computer Hardware","NASDAQ"],
  ["ETN","Eaton Corporation plc","Industrials","Electrical Equipment & Parts","NYSE"],
  ["TBB","AT&T Inc. 5.35% GLB NTS 66","Communication Services","Telecommunications Services","NYSE"],
  ["PFE","Pfizer Inc.","Healthcare","Drug Manufacturers - General","NYSE"],
  ["IBKR","Interactive Brokers Group, Inc.","Financial Services","Investment - Banking & Investment Services","NASDAQ"],
  ["BUD","Anheuser-Busch InBev SA/NV","Consumer Defensive","Beverages - Alcoholic","NYSE"],
  ["BX","Blackstone Inc.","Financial Services","Asset Management","NYSE"],
  ["UBER","Uber Technologies, Inc.","Technology","Software - Application","NYSE"],
  ["DHR","Danaher Corporation","Healthcare","Medical - Diagnostics & Research","NYSE"],
  ["GLW","Corning Inc","Technology","Hardware, Equipment & Parts","NYSE"],
  ["TJX","The TJX Companies, Inc.","Consumer Cyclical","Apparel - Retail","NYSE"],
  ["SONY","Sony Group Corporation","Technology","Consumer Electronics","NYSE"],
  ["PBR","Petróleo Brasileiro S.A. - Petrobras","Energy","Oil & Gas Integrated","NYSE"],
  ["NOW","ServiceNow, Inc.","Technology","Software - Application","NYSE"],
  ["BKNG","Booking Holdings Inc.","Consumer Cyclical","Travel Services","NASDAQ"],
  ["MFG","Mizuho Financial Group, Inc.","Financial Services","Banks - Regional","NYSE"],
  ["NEM","Newmont Corporation","Basic Materials","Gold","NYSE"],
  ["UL","Unilever PLC","Consumer Defensive","Household & Personal Products","NYSE"],
  ["CB","Chubb Limited","Financial Services","Insurance - Property & Casualty","NYSE"],
  ["VRTX","Vertex Pharmaceuticals Incorporated","Healthcare","Biotechnology","NASDAQ"],
  ["BMY","Bristol-Myers Squibb Company","Healthcare","Drug Manufacturers - General","NYSE"],
  ["ISRG","Intuitive Surgical, Inc.","Healthcare","Medical - Instruments & Supplies","NASDAQ"],
  ["COF","Capital One Financial Corporation","Financial Services","Financial - Credit Services","NYSE"],
  ["PGR","The Progressive Corporation","Financial Services","Insurance - Property & Casualty","NYSE"],
  ["PLD","Prologis, Inc.","Real Estate","REIT - Industrial","NYSE"],
  ["LMT","Lockheed Martin Corporation","Industrials","Aerospace & Defense","NYSE"],
  ["BMO","Bank of Montreal","Financial Services","Banks - Diversified","NYSE"],
  ["CVS","CVS Health Corp.","Healthcare","Medical - Healthcare Plans","NYSE"],
  ["SPGI","S&P Global Inc.","Financial Services","Financial - Data & Stock Exchanges","NYSE"],
  ["BP","BP p.l.c.","Energy","Oil & Gas Integrated","NYSE"],
  ["BTI","British American Tobacco p.l.c.","Consumer Defensive","Tobacco","NYSE"],
  ["PH","Parker-Hannifin Corporation","Industrials","Industrial - Machinery","NYSE"],
  ["MDT","Medtronic plc","Healthcare","Medical - Devices","NYSE"],
  ["FTNT","Fortinet, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["MO","Altria Group, Inc.","Consumer Defensive","Tobacco","NYSE"],
  ["MPC","Marathon Petroleum Corporation","Energy","Oil & Gas Refining & Marketing","NYSE"],
  ["SNOW","Snowflake Inc.","Technology","Software - Application","NYSE"],
  ["BNS","The Bank of Nova Scotia","Financial Services","Banks - Diversified","NYSE"],
  ["SBUX","Starbucks Corporation","Consumer Cyclical","Restaurants","NASDAQ"],
  ["HDB","HDFC Bank Limited","Financial Services","Banks - Regional","NYSE"],
  ["BNY","Bank of New York Mellon Corp","Financial Services","Investment - Banking & Investment Services","NYSE"],
  ["VLO","Valero Energy Corporation","Energy","Oil & Gas Refining & Marketing","NYSE"],
  ["PDD","PDD Holdings Inc.","Consumer Cyclical","Specialty Retail","NASDAQ"],
  ["NET","Cloudflare, Inc.","Technology","Software - Infrastructure","NYSE"],
  ["LOW","Lowe's Companies, Inc.","Consumer Cyclical","Home Improvement","NYSE"],
  ["ACN","Accenture plc","Technology","Information Technology Services","NYSE"],
  ["EQNR","Equinor ASA","Energy","Oil & Gas Integrated","NYSE"],
  ["SPOT","Spotify Technology S.A.","Communication Services","Internet Content & Information","NYSE"],
  ["ADP","Automatic Data Processing, Inc.","Technology","Software - Application","NASDAQ"],
  ["CM","Canadian Imperial Bank of Commerce","Financial Services","Banks - Diversified","NYSE"],
  ["CNQ","Canadian Natural Resources Limited","Energy","Oil & Gas Exploration & Production","NYSE"],
  ["APP","AppLovin Corporation","Technology","Software - Application","NASDAQ"],
  ["ENB","Enbridge Inc.","Energy","Oil & Gas Midstream","NYSE"],
  ["SOJE","Southern Company (The) Series 2","Utilities","Regulated Electric","NYSE"],
  ["ING","ING Groep N.V.","Financial Services","Banks - Diversified","NYSE"],
  ["SOMN","The Southern Company","Utilities","Regulated Electric","NYSE"],
  ["PSX","Phillips 66","Energy","Oil & Gas Refining & Marketing","NYSE"],
  ["SYK","Stryker Corporation","Healthcare","Medical - Devices","NYSE"],
  ["IBN","ICICI Bank Limited","Financial Services","Banks - Regional","NYSE"],
  ["MCK","McKesson Corporation","Healthcare","Medical - Distribution","NYSE"],
  ["SMFG","Sumitomo Mitsui Financial Group, Inc.","Financial Services","Banks - Diversified","NYSE"],
  ["CEG","Constellation Energy Corporation","Utilities","Independent Power Producers","NASDAQ"],
  ["SNY","Sanofi","Healthcare","Drug Manufacturers - General","NASDAQ"],
  ["FCX","Freeport-McMoRan Inc.","Basic Materials","Copper","NYSE"],
  ["HOOD","Robinhood Markets, Inc.","Financial Services","Financial - Capital Markets","NASDAQ"],
  ["EQIX","Equinix, Inc.","Real Estate","REIT - Specialty","NASDAQ"],
  ["SO","The Southern Company","Utilities","Regulated Electric","NYSE"],
  ["AEM","Agnico Eagle Mines Limited","Basic Materials","Gold","NYSE"],
  ["ABNB","Airbnb, Inc.","Consumer Cyclical","Travel Services","NASDAQ"],
  ["ADBE","Adobe Inc.","Technology","Software - Application","NASDAQ"],
  ["CME","CME Group Inc.","Financial Services","Financial - Data & Stock Exchanges","NASDAQ"],
  ["USB","U.S. Bancorp","Financial Services","Banks - Diversified","NYSE"],
  ["PNC","The PNC Financial Services Group, Inc.","Financial Services","Banks - Regional","NYSE"],
  ["TT","Trane Technologies plc","Industrials","Industrial - Machinery","NYSE"],
  ["MELI","MercadoLibre, Inc.","Consumer Cyclical","Specialty Retail","NASDAQ"],
  ["GSK","GSK plc","Healthcare","Drug Manufacturers - General","NYSE"],
  ["GD","General Dynamics Corporation","Industrials","Aerospace & Defense","NYSE"],
  ["VRT","Vertiv Holdings Co","Industrials","Electrical Equipment & Parts","NYSE"],
  ["BNH","Brookfield Finance Inc.","Financial Services","Asset Management","NYSE"],
  ["DUK","Duke Energy Corporation","Utilities","Regulated Electric","NYSE"],
  ["PWR","Quanta Services, Inc.","Industrials","Engineering & Construction","NYSE"],
  ["ITUB","Itaú Unibanco Holding S.A.","Financial Services","Banks","NYSE"],
  ["HCA","HCA Healthcare, Inc.","Healthcare","Medical - Care Facilities","NYSE"],
  ["HWM","Howmet Aerospace Inc.","Industrials","Aerospace & Defense","NYSE"],
  ["CSX","CSX Corporation","Industrials","Railroads","NASDAQ"],
  ["KKR","KKR & Co. Inc.","Financial Services","Asset Management","NYSE"],
  ["ELV","Elevance Health Inc.","Healthcare","Medical - Healthcare Plans","NYSE"],
  ["BNJ","Brookfield Finance Inc. 4.50% P","Financial Services","Asset Management","NYSE"],
  ["CMCSA","Comcast Corporation","Communication Services","Telecommunications Services","NASDAQ"],
  ["WMB","The Williams Companies, Inc.","Energy","Oil & Gas Midstream","NYSE"],
  ["BCS","Barclays PLC","Financial Services","Banks - Diversified","NYSE"],
  ["ASX","ASE Technology Holding Co., Ltd.","Technology","Semiconductors","NYSE"],
  ["DASH","DoorDash, Inc.","Communication Services","Internet Content & Information","NASDAQ"],
  ["ICE","Intercontinental Exchange, Inc.","Financial Services","Financial - Data & Stock Exchanges","NYSE"],
  ["JCI","Johnson Controls International plc","Basic Materials","Construction Materials","NYSE"],
  ["WM","Waste Management, Inc.","Industrials","Waste Management","NYSE"],
  ["MAR","Marriott International, Inc.","Consumer Cyclical","Travel Lodging","NASDAQ"],
  ["INTU","Intuit Inc.","Technology","Software - Application","NASDAQ"],
  ["LYG","Lloyds Banking Group plc","Financial Services","Banks - Regional","NYSE"],
  ["EPD","Enterprise Products Partners L.P.","Energy","Oil & Gas Midstream","NYSE"],
  ["BN","Brookfield Corporation","Financial Services","Asset Management","NYSE"],
  ["UPS","United Parcel Service, Inc.","Industrials","Integrated Freight & Logistics","NYSE"],
  ["MRSH","Marsh & McLennan Companies, Inc.","Financial Services","Insurance - Brokers","NYSE"],
  ["MNST","Monster Beverage Corporation","Consumer Defensive","Beverages - Non-Alcoholic","NASDAQ"],
  ["MMM","3M Company","Industrials","Conglomerates","NYSE"],
  ["SLB","Slb N.V.","Energy","Oil & Gas Equipment & Services","NYSE"],
  ["EMR","Emerson Electric Co.","Industrials","Industrial - Machinery","NYSE"],
  ["E","Eni S.p.A.","Energy","Oil & Gas Integrated","NYSE"],
  ["REGN","Regeneron Pharmaceuticals, Inc.","Healthcare","Biotechnology","NASDAQ"],
  ["SU","Suncor Energy Inc.","Energy","Oil & Gas Integrated","NYSE"],
  ["MCO","Moody's Corporation","Financial Services","Financial - Data & Stock Exchanges","NYSE"],
  ["AMT","American Tower Corporation","Real Estate","REIT - Specialty","NYSE"],
  ["MDLZ","Mondelez International, Inc.","Consumer Defensive","Food Confectioners","NASDAQ"],
  ["CTAS","Cintas Corporation","Industrials","Specialty Business Services","NASDAQ"],
  ["DDOG","Datadog, Inc.","Technology","Software - Application","NASDAQ"],
  ["EOG","EOG Resources, Inc.","Energy","Oil & Gas Exploration & Production","NYSE"],
  ["CDNS","Cadence Design Systems, Inc.","Technology","Software - Application","NASDAQ"],
  ["CP","Canadian Pacific Kansas City Ltd.","Industrials","Railroads","NYSE"],
  ["GM","General Motors Company","Consumer Cyclical","Auto - Manufacturers","NYSE"],
  ["CVNA","Carvana Co.","Consumer Cyclical","Auto - Dealerships","NYSE"],
  ["SHW","The Sherwin-Williams Company","Basic Materials","Chemicals - Specialty","NYSE"],
  ["MSI","Motorola Solutions, Inc.","Technology","Communication Equipment","NYSE"],
  ["NGG","National Grid plc","Utilities","Regulated Electric","NYSE"],
  ["TRV","The Travelers Companies, Inc.","Financial Services","Insurance - Property & Casualty","NYSE"],
  ["ECL","Ecolab Inc.","Basic Materials","Chemicals - Specialty","NYSE"],
  ["ITW","Illinois Tool Works Inc.","Industrials","Industrial - Machinery","NYSE"],
  ["BE","Bloom Energy Corporation","Industrials","Electrical Equipment & Parts","NYSE"],
  ["SNPS","Synopsys, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["CMI","Cummins Inc.","Industrials","Industrial - Machinery","NYSE"],
  ["DB","Deutsche Bank AG","Financial Services","Banks - Regional","NYSE"],
  ["BAM","Brookfield Asset Management Ltd.","Financial Services","Asset Management","NYSE"],
  ["ET","Energy Transfer LP","Energy","Oil & Gas Midstream","NYSE"],
  ["CI","Cigna Corporation","Healthcare","Medical - Healthcare Plans","NYSE"],
  ["APOS","Apollo Global Management, Inc.","Financial Services","Asset Management","NYSE"],
  ["NTES","NetEase, Inc.","Technology","Electronic Gaming & Multimedia","NASDAQ"],
  ["FDX","FedEx Corporation","Industrials","Integrated Freight & Logistics","NYSE"],
  ["NOC","Northrop Grumman Corporation","Industrials","Aerospace & Defense","NYSE"],
  ["APO","Apollo Global Management, Inc.","Financial Services","Asset Management","NYSE"],
  ["CNI","Canadian National Railway Company","Industrials","Railroads","NYSE"],
  ["HPE","Hewlett Packard Enterprise Company","Technology","Computer Hardware","NYSE"],
  ["B","Barrick Mining Corporation","Basic Materials","Gold","NYSE"],
  ["LITE","Lumentum Holdings Inc.","Technology","Communication Equipment","NASDAQ"],
  ["NU","Nu Holdings Ltd.","Financial Services","Banks - Regional","NYSE"],
  ["NSC","Norfolk Southern Corporation","Industrials","Railroads","NYSE"],
  ["MFC","Manulife Financial Corporation","Financial Services","Insurance - Life","NYSE"],
  ["ROST","Ross Stores, Inc.","Consumer Cyclical","Apparel - Retail","NASDAQ"],
  ["RACE","Ferrari N.V.","Consumer Cyclical","Auto - Manufacturers","NYSE"],
  ["ORLY","O'Reilly Automotive, Inc.","Consumer Cyclical","Specialty Retail","NASDAQ"],
  ["TGT","Target Corporation","Consumer Defensive","Discount Stores","NYSE"],
  ["WBD","Warner Bros. Discovery, Inc.","Communication Services","Entertainment","NASDAQ"],
  ["CL","Colgate-Palmolive Company","Consumer Defensive","Household & Personal Products","NYSE"],
  ["SATA","Strive Inc. Perp. Pfd. Series A","Financial Services","Asset Management","NASDAQ"],
  ["RCL","Royal Caribbean Cruises Ltd.","Consumer Cyclical","Travel Services","NYSE"],
  ["HLT","Hilton Worldwide Holdings Inc.","Consumer Cyclical","Travel Lodging","NYSE"],
  ["KMI","Kinder Morgan, Inc.","Energy","Oil & Gas Midstream","NYSE"],
  ["DLR","Digital Realty Trust, Inc.","Real Estate","REIT - Specialty","NYSE"],
  ["WPM","Wheaton Precious Metals Corp.","Basic Materials","Gold","NYSE"],
  ["AMX","América Móvil, S.A.B. de C.V.","Communication Services","Telecommunications Services","NYSE"],
  ["RSG","Republic Services, Inc.","Industrials","Waste Management","NYSE"],
  ["AEP","American Electric Power Company, Inc.","Utilities","Regulated Electric","NASDAQ"],
  ["SPG","Simon Property Group, Inc.","Real Estate","REIT - Retail","NYSE"],
  ["APD","Air Products and Chemicals, Inc.","Basic Materials","Chemicals - Specialty","NYSE"],
  ["AON","Aon plc","Financial Services","Insurance - Brokers","NYSE"],
  ["VALE","Vale S.A.","Basic Materials","Industrial Materials","NYSE"],
  ["ALL","The Allstate Corporation","Financial Services","Insurance - Property & Casualty","NYSE"],
  ["SE","Sea Limited","Consumer Cyclical","Specialty Retail","NYSE"],
  ["PCAR","PACCAR Inc","Industrials","Industrial - Machinery","NASDAQ"],
  ["TRP","TC Energy Corporation","Energy","Oil & Gas Midstream","NYSE"],
  ["HON","Honeywell International Inc.","Industrials","Conglomerates","NASDAQ"],
  ["BSX","Boston Scientific Corporation","Healthcare","Medical - Devices","NYSE"],
  ["TDG","TransDigm Group Incorporated","Industrials","Aerospace & Defense","NYSE"],
  ["TFC","Truist Financial Corporation","Financial Services","Banks - Regional","NYSE"],
  ["TRGP","Targa Resources Corp.","Energy","Oil & Gas Midstream","NYSE"],
  ["AJG","Arthur J. Gallagher & Co.","Financial Services","Insurance - Brokers","NYSE"],
  ["COR","Cencora, Inc.","Healthcare","Medical - Distribution","NYSE"],
  ["MET","MetLife, Inc.","Financial Services","Insurance - Life","NYSE"],
  ["URI","United Rentals, Inc.","Industrials","Rental & Leasing Services","NYSE"],
  ["CVE","Cenovus Energy Inc.","Energy","Oil & Gas Integrated","NYSE"],
  ["ARGX","argenx SE","Healthcare","Biotechnology","NASDAQ"],
  ["OXY","Occidental Petroleum Corporation","Energy","Oil & Gas Exploration & Production","NYSE"],
  ["MPLX","MPLX Lp","Energy","Oil & Gas Midstream","NYSE"],
  ["OKE","ONEOK, Inc.","Energy","Oil & Gas Midstream","NYSE"],
  ["GWW","W.W. Grainger, Inc.","Industrials","Industrial - Distribution","NYSE"],
  ["TEL","TE Connectivity plc","Technology","Semiconductors","NYSE"],
  ["RELX","RELX Plc","Industrials","Specialty Business Services","NYSE"],
  ["BKR","Baker Hughes Company","Energy","Oil & Gas Equipment & Services","NASDAQ"],
  ["CRH","CRH plc","Basic Materials","Construction Materials","NYSE"],
  ["MPWR","Monolithic Power Systems, Inc.","Technology","Semiconductors","NASDAQ"],
  ["AFL","Aflac Incorporated","Financial Services","Insurance - Life","NYSE"],
  ["LNG","Cheniere Energy, Inc.","Energy","Oil & Gas Midstream","NYSE"],
  ["NUE","Nucor Corporation","Basic Materials","Steel","NYSE"],
  ["TER","Teradyne, Inc.","Technology","Semiconductors","NASDAQ"],
  ["FANG","Diamondback Energy, Inc.","Energy","Oil & Gas Exploration & Production","NASDAQ"],
  ["TAK","Takeda Pharmaceutical Company Limited","Healthcare","Drug Manufacturers - Specialty & Generic","NYSE"],
  ["COHR","Coherent, Inc.","Technology","Hardware, Equipment & Parts","NYSE"],
  ["NOK","Nokia Oyj","Technology","Communication Equipment","NYSE"],
  ["D","Dominion Energy, Inc.","Utilities","Regulated Electric","NYSE"],
  ["MT","ArcelorMittal S.A.","Basic Materials","Steel","NYSE"],
  ["NXPI","NXP Semiconductors N.V.","Technology","Semiconductors","NASDAQ"],
  ["CTVA","Corteva, Inc.","Basic Materials","Agricultural Inputs","NYSE"],
  ["FAST","Fastenal Company","Industrials","Industrial - Distribution","NASDAQ"],
  ["FIX","Comfort Systems USA, Inc.","Industrials","Engineering & Construction","NYSE"],
  ["KEYS","Keysight Technologies, Inc.","Technology","Hardware, Equipment & Parts","NYSE"],
  ["O","Realty Income Corporation","Real Estate","REIT - Retail","NYSE"],
  ["F","Ford Motor Company","Consumer Cyclical","Auto - Manufacturers","NYSE"],
  ["CAH","Cardinal Health, Inc.","Healthcare","Medical - Distribution","NYSE"],
  ["UMC","United Microelectronics Corporation","Technology","Semiconductors","NYSE"],
  ["DVN","Devon Energy Corporation","Energy","Oil & Gas Exploration & Production","NYSE"],
  ["PSA","Public Storage","Real Estate","REIT - Industrial","NYSE"],
  ["SRE","Sempra","Utilities","Diversified Utilities","NYSE"],
  ["NBIS","Nebius Group N.V.","Technology","Software - Infrastructure","NASDAQ"],
  ["MRNA","Moderna, Inc.","Healthcare","Biotechnology","NASDAQ"],
  ["NKE","NIKE, Inc.","Consumer Cyclical","Apparel - Footwear & Accessories","NYSE"],
  ["AME","AMETEK, Inc.","Industrials","Electrical Equipment & Parts","NYSE"],
  ["STT","State Street Corporation","Financial Services","Asset Management","NYSE"],
  ["AU","AngloGold Ashanti plc","Basic Materials","Gold","NYSE"],
  ["GRMN","Garmin Ltd.","Technology","Hardware, Equipment & Parts","NYSE"],
  ["DAL","Delta Air Lines, Inc.","Industrials","Airlines, Airports & Air Services","NYSE"],
  ["NDAQ","Nasdaq, Inc.","Financial Services","Financial - Data & Stock Exchanges","NASDAQ"],
  ["FNV","Franco-Nevada Corporation","Basic Materials","Gold","NYSE"],
  ["EW","Edwards Lifesciences Corporation","Healthcare","Medical - Devices","NYSE"],
  ["AMP","Ameriprise Financial, Inc.","Financial Services","Asset Management","NYSE"],
  ["VST","Vistra Corp.","Utilities","Independent Power Producers","NYSE"],
  ["ETR","Entergy Corporation","Utilities","Regulated Electric","NYSE"],
  ["FITB","Fifth Third Bancorp","Financial Services","Banks - Regional","NYSE"],
  ["ELC","Entergy Louisiana, LLC COLLATERAL TR MT","Utilities","Regulated Electric","NYSE"],
  ["ALAB","Astera Labs, Inc. Common Stock","Technology","Semiconductors","NASDAQ"],
  ["HONA","Honeywell Aerospace Inc","Industrials","Aerospace & Defense","NASDAQ"],
  ["CRWV","CoreWeave, Inc. Class A Common Stock","Technology","Software - Infrastructure","NASDAQ"],
  ["BDX","Becton, Dickinson and Company","Healthcare","Medical - Instruments & Supplies","NYSE"],
  ["WDAY","Workday, Inc.","Technology","Software - Application","NASDAQ"],
  ["HUM","Humana Inc.","Healthcare","Medical - Healthcare Plans","NYSE"],
  ["DEO","Diageo plc","Consumer Defensive","Beverages - Alcoholic","NYSE"],
  ["CIEN","Ciena Corporation","Technology","Communication Equipment","NYSE"],
  ["WAB","Westinghouse Air Brake Technologies Corporation","Industrials","Railroads","NYSE"],
  ["TEAM","Atlassian Corporation","Technology","Software - Application","NASDAQ"],
  ["XEL","Xcel Energy Inc.","Utilities","Regulated Electric","NASDAQ"],
  ["XYZ","Block, Inc.","Technology","Software - Infrastructure","NYSE"],
  ["AZO","AutoZone, Inc.","Consumer Cyclical","Specialty Retail","NYSE"],
  ["ABEV","Ambev S.A.","Consumer Defensive","Beverages - Alcoholic","NYSE"],
  ["ROK","Rockwell Automation, Inc.","Industrials","Industrial - Machinery","NYSE"],
  ["NTRA","Natera, Inc.","Healthcare","Medical - Diagnostics & Research","NASDAQ"],
  ["CARR","Carrier Global Corporation","Industrials","Industrial - Machinery","NYSE"],
  ["EBAY","eBay Inc.","Consumer Cyclical","Specialty Retail","NASDAQ"],
  ["CMG","Chipotle Mexican Grill, Inc.","Consumer Cyclical","Restaurants","NYSE"],
  ["LHX","L3Harris Technologies, Inc.","Industrials","Aerospace & Defense","NYSE"],
  ["PYPL","PayPal Holdings, Inc.","Financial Services","Financial - Credit Services","NASDAQ"],
  ["CCEP","Coca-Cola Europacific Partners PLC","Consumer Defensive","Beverages - Non-Alcoholic","NASDAQ"],
  ["COIN","Coinbase Global, Inc.","Financial Services","Financial - Data & Stock Exchanges","NASDAQ"],
  ["WDS","Woodside Energy Group Ltd","Energy","Oil & Gas Exploration & Production","NYSE"],
  ["STM","STMicroelectronics N.V.","Technology","Semiconductors","NYSE"],
  ["EXC","Exelon Corporation","Utilities","Regulated Electric","NASDAQ"],
  ["ADSK","Autodesk, Inc.","Technology","Software - Application","NASDAQ"],
  ["KB","KB Financial Group Inc.","Financial Services","Banks - Regional","NYSE"],
  ["INFY","Infosys Limited","Technology","Information Technology Services","NYSE"],
  ["SLF","Sun Life Financial Inc.","Financial Services","Insurance - Diversified","NYSE"],
  ["BSBR","Banco Santander (Brasil) S.A.","Financial Services","Banks - Regional","NYSE"],
  ["VTR","Ventas, Inc.","Real Estate","REIT - Healthcare Facilities","NYSE"],
  ["HEI","HEICO Corporation","Industrials","Aerospace & Defense","NYSE"],
  ["IX","ORIX Corporation","Financial Services","Financial - Credit Services","NYSE"],
  ["CBRS","Cerebras Systems Inc.","Technology","Semiconductors","NASDAQ"],
  ["RVMD","Revolution Medicines, Inc.","Healthcare","Biotechnology","NASDAQ"],
  ["ARES","Ares Management Corporation","Financial Services","Asset Management","NYSE"],
  ["FERG","Ferguson plc","Industrials","Industrial - Distribution","NYSE"],
  ["KDP","Keurig Dr Pepper Inc.","Consumer Defensive","Beverages - Non-Alcoholic","NASDAQ"],
  ["MSTR","Strategy Inc","Technology","Software - Application","NASDAQ"],
  ["CCJ","Cameco Corporation","Energy","Uranium","NYSE"],
  ["VEEV","Veeva Systems Inc.","Technology","Software - Application","NYSE"],
  ["IQV","IQVIA Holdings Inc.","Healthcare","Medical - Diagnostics & Research","NYSE"],
  ["TEVA","Teva Pharmaceutical Industries Limited","Healthcare","Drug Manufacturers - Specialty & Generic","NYSE"],
  ["ADM","Archer-Daniels-Midland Company","Consumer Defensive","Agricultural Farm Products","NYSE"],
  ["TRI","Thomson Reuters Corporation","Industrials","Specialty Business Services","NASDAQ"],
  ["PRU","Prudential Financial, Inc.","Financial Services","Insurance - Life","NYSE"],
  ["HMC","Honda Motor Co., Ltd.","Consumer Cyclical","Auto - Manufacturers","NYSE"],
  ["PAYX","Paychex, Inc.","Industrials","Staffing & Employment Services","NASDAQ"],
  ["GFI","Gold Fields Limited","Basic Materials","Gold","NYSE"],
  ["HLN","Haleon plc","Healthcare","Drug Manufacturers - Specialty & Generic","NYSE"],
  ["TTWO","Take-Two Interactive Software, Inc.","Technology","Electronic Gaming & Multimedia","NASDAQ"],
  ["A","Agilent Technologies, Inc.","Healthcare","Medical - Diagnostics & Research","NYSE"],
  ["FER","Ferrovial SE","Industrials","Engineering & Construction","NASDAQ"],
  ["WCN","Waste Connections, Inc.","Industrials","Waste Management","NYSE"],
  ["FMX","Fomento Económico Mexicano, S.A.B. de C.V.","Consumer Defensive","Beverages - Alcoholic","NYSE"],
  ["CBRE","CBRE Group, Inc.","Real Estate","Real Estate - Services","NYSE"],
  ["IDXX","IDEXX Laboratories, Inc.","Healthcare","Medical - Diagnostics & Research","NASDAQ"],
  ["VOD","Vodafone Group Public Limited Company","Communication Services","Telecommunications Services","NASDAQ"],
  ["FLEX","Flex Ltd.","Technology","Hardware, Equipment & Parts","NASDAQ"],
  ["MSCI","MSCI Inc.","Financial Services","Financial - Data & Stock Exchanges","NYSE"],
  ["AIG","American International Group, Inc.","Financial Services","Insurance - Diversified","NYSE"],
  ["YUM","Yum! Brands, Inc.","Consumer Cyclical","Restaurants","NYSE"],
  ["LYV","Live Nation Entertainment, Inc.","Communication Services","Entertainment","NYSE"],
  ["PFH","Prudential Financial, Inc. 4.125% Junior Subordinated Notes due 2060","Financial Services","Insurance - Diversified","NYSE"],
  ["SYY","Sysco Corporation","Consumer Defensive","Food Distribution","NYSE"],
  ["ED","Consolidated Edison, Inc.","Utilities","Regulated Electric","NYSE"],
  ["ROP","Roper Technologies, Inc.","Technology","Software - Application","NASDAQ"],
  ["MCHP","Microchip Technology Incorporated","Technology","Semiconductors","NASDAQ"],
  ["AXON","Axon Enterprise, Inc.","Industrials","Aerospace & Defense","NASDAQ"],
  ["SHG","Shinhan Financial Group Co., Ltd.","Financial Services","Banks - Regional","NYSE"],
  ["JD","JD.com, Inc.","Consumer Cyclical","Specialty Retail","NASDAQ"],
  ["DHI","D.R. Horton, Inc.","Consumer Cyclical","Residential Construction","NYSE"],
  ["BBD","Banco Bradesco S.A.","Financial Services","Banks - Regional","NYSE"],
  ["VG","Venture Global, Inc.","Energy","Oil & Gas Midstream","NYSE"],
  ["NTR","Nutrien Ltd.","Basic Materials","Agricultural Inputs","NYSE"],
  ["PCG","PG&E Corporation","Utilities","Regulated Electric","NYSE"],
  ["ODFL","Old Dominion Freight Line, Inc.","Industrials","Trucking","NASDAQ"],
  ["HIG","The Hartford Insurance Group, Inc.","Financial Services","Insurance - Diversified","NYSE"],
  ["CLS","Celestica Inc.","Technology","Hardware, Equipment & Parts","NYSE"],
  ["VIK","Viking Holdings Ltd","Consumer Cyclical","Travel Services","NYSE"],
  ["RKT","Rocket Companies, Inc.","Financial Services","Financial - Mortgages","NYSE"],
  ["EC","Ecopetrol S.A.","Energy","Oil & Gas Integrated","NYSE"],
  ["NWG","NatWest Group plc","Financial Services","Banks - Regional","NYSE"],
  ["ONC","BeOne Medicines AG","Healthcare","Biotechnology","NASDAQ"],
  ["PEG","Public Service Enterprise Group Incorporated","Utilities","Regulated Electric","NYSE"],
  ["NTAP","NetApp, Inc.","Technology","Computer Hardware","NASDAQ"],
  ["RKLB","Rocket Lab USA, Inc.","Industrials","Aerospace & Defense","NASDAQ"],
  ["HSY","The Hershey Company","Consumer Defensive","Food Confectioners","NYSE"],
  ["TWLO","Twilio Inc.","Technology","Software - Infrastructure","NYSE"],
  ["EL","The Estée Lauder Companies Inc.","Consumer Defensive","Household & Personal Products","NYSE"],
  ["KR","The Kroger Co.","Consumer Defensive","Grocery Stores","NYSE"],
  ["BBDO","Banco Bradesco S.A.","Financial Services","Banks - Regional","NYSE"],
  ["MTB","M&T Bank Corporation","Financial Services","Banks - Regional","NYSE"],
  ["UAL","United Airlines Holdings, Inc.","Industrials","Airlines, Airports & Air Services","NASDAQ"],
  ["CHT","Chunghwa Telecom Co., Ltd.","Communication Services","Telecommunications Services","NYSE"],
  ["EQT","EQT Corporation","Energy","Oil & Gas Exploration & Production","NYSE"],
  ["KGC","Kinross Gold Corporation","Basic Materials","Gold","NYSE"],
  ["WEC","WEC Energy Group, Inc.","Utilities","Regulated Electric","NYSE"],
  ["NTRS","Northern Trust Corporation","Financial Services","Asset Management","NASDAQ"],
  ["PPLC","PPL Corporation","Utilities","Regulated Electric","NYSE"],
  ["KVUE","Kenvue Inc.","Consumer Defensive","Household & Personal Products","NYSE"],
  ["STLD","Steel Dynamics, Inc.","Basic Materials","Steel","NASDAQ"],
  ["ESLT","Elbit Systems Ltd.","Industrials","Aerospace & Defense","NASDAQ"],
  ["HBAN","Huntington Bancshares Incorporated","Financial Services","Banks - Regional","NASDAQ"],
  ["STRC","Strategy Inc","Technology","Software - Application","NASDAQ"],
  ["ACGL","Arch Capital Group Ltd.","Financial Services","Insurance - Diversified","NASDAQ"],
  ["IRM","Iron Mountain Incorporated","Real Estate","REIT - Specialty","NYSE"],
  ["RJF","Raymond James Financial, Inc.","Financial Services","Asset Management","NYSE"],
  ["PUK","Prudential plc","Financial Services","Insurance - Life","NYSE"],
  ["CQP","Cheniere Energy Partners, L.P.","Energy","Oil & Gas Midstream","NYSE"],
  ["ALNY","Alnylam Pharmaceuticals, Inc.","Healthcare","Biotechnology","NASDAQ"],
  ["EME","EMCOR Group, Inc.","Industrials","Engineering & Construction","NYSE"],
  ["ERIC","Telefonaktiebolaget LM Ericsson (publ)","Technology","Communication Equipment","NASDAQ"],
  ["KMB","Kimberly-Clark Corporation","Consumer Defensive","Household & Personal Products","NASDAQ"],
  ["UI","Ubiquiti Inc.","Technology","Communication Equipment","NYSE"],
  ["VMC","Vulcan Materials Company","Basic Materials","Construction Materials","NYSE"],
  ["ALC","Alcon Inc.","Healthcare","Medical - Specialties","NYSE"],
  ["CNC","Centene Corp.","Healthcare","Medical - Healthcare Plans","NYSE"],
  ["CCI","Crown Castle Inc.","Real Estate","REIT - Specialty","NYSE"],
  ["RBLX","Roblox Corporation","Technology","Electronic Gaming & Multimedia","NYSE"],
  ["DXCM","DexCom, Inc.","Healthcare","Medical - Devices","NASDAQ"],
  ["RMD","ResMed Inc.","Healthcare","Medical - Instruments & Supplies","NYSE"],
  ["BIIB","Biogen Inc.","Healthcare","Drug Manufacturers - General","NASDAQ"],
  ["TECK","Teck Resources Limited","Basic Materials","Copper","NYSE"],
  ["JBL","Jabil Inc.","Technology","Hardware, Equipment & Parts","NYSE"],
  ["EXPE","Expedia Group, Inc.","Consumer Cyclical","Travel Services","NASDAQ"],
  ["P","Everpure, Inc.","Technology","Computer Hardware","NYSE"],
  ["STRF","MicroStrategy Incorporated 10.00% Series A Perpetual Strife Preferred Stock","Technology","Software - Application","NASDAQ"],
  ["BIDU","Baidu, Inc.","Communication Services","Internet Content & Information","NASDAQ"],
  ["NMR","Nomura Holdings, Inc.","Financial Services","Financial - Capital Markets","NYSE"],
  ["CCL","Carnival Corporation & plc","Consumer Cyclical","Travel Services","NYSE"],
  ["ZTS","Zoetis Inc.","Healthcare","Drug Manufacturers - Specialty & Generic","NYSE"],
  ["TS","Tenaris S.A.","Energy","Oil & Gas Equipment & Services","NYSE"],
  ["ILMN","Illumina, Inc.","Healthcare","Medical - Diagnostics & Research","NASDAQ"],
  ["MLM","Martin Marietta Materials, Inc.","Basic Materials","Construction Materials","NYSE"],
  ["BAP","Credicorp Ltd.","Financial Services","Banks - Diversified","NYSE"],
  ["HAL","Halliburton Company","Energy","Oil & Gas Equipment & Services","NYSE"],
  ["MDB","MongoDB, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["WAT","Waters Corporation","Healthcare","Medical - Diagnostics & Research","NYSE"],
  ["SUNB","Sunbelt Rentals Holdings Inc","Industrials","Rental & Leasing Services","NYSE"],
  ["HPQ","HP Inc.","Technology","Computer Hardware","NYSE"],
  ["RDDT","Reddit, Inc.","Communication Services","Internet Content & Information","NYSE"],
  ["CRDO","Credo Technology Group Holding Ltd","Technology","Semiconductors","NASDAQ"],
  ["FTI","TechnipFMC plc","Energy","Oil & Gas Equipment & Services","NYSE"],
  ["ROIV","Roivant Sciences Ltd.","Healthcare","Biotechnology","NASDAQ"],
  ["CFG","Citizens Financial Group, Inc.","Financial Services","Banks - Regional","NYSE"],
  ["WTW","Willis Towers Watson Public Limited Company","Financial Services","Insurance - Brokers","NASDAQ"],
  ["AEE","Ameren Corporation","Utilities","Regulated Electric","NYSE"],
  ["GEHC","GE HealthCare Technologies Inc.","Healthcare","Medical - Devices","NASDAQ"],
  ["KHC","The Kraft Heinz Company","Consumer Defensive","Packaged Foods","NASDAQ"],
  ["EXR","Extra Space Storage Inc.","Real Estate","REIT - Industrial","NYSE"],
  ["IR","Ingersoll Rand Inc.","Industrials","Industrial - Machinery","NYSE"],
  ["FOXA","Fox Corporation","Communication Services","Entertainment","NASDAQ"],
  ["CPRT","Copart, Inc.","Industrials","Specialty Business Services","NASDAQ"],
  ["OKTA","Okta, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["PBA","Pembina Pipeline Corporation","Energy","Oil & Gas Midstream","NYSE"],
  ["JBS","Jbs N.V.","Consumer Defensive","Packaged Foods","NYSE"],
  ["ZM","Zoom Communications, Inc.","Technology","Software - Application","NASDAQ"],
  ["DTE","DTE Energy Company","Utilities","Regulated Electric","NYSE"],
  ["AWK","American Water Works Company, Inc.","Utilities","Regulated Water","NYSE"],
  ["LPLA","LPL Financial Holdings Inc.","Financial Services","Financial - Capital Markets","NASDAQ"],
  ["FTS","Fortis Inc.","Utilities","Regulated Electric","NYSE"],
  ["TDY","Teledyne Technologies Incorporated","Technology","Hardware, Equipment & Parts","NYSE"],
  ["LVS","Las Vegas Sands Corp.","Consumer Cyclical","Gambling, Resorts & Casinos","NYSE"],
  ["INSM","Insmed Incorporated","Healthcare","Biotechnology","NASDAQ"],
  ["RYAAY","Ryanair Holdings plc","Industrials","Airlines, Airports & Air Services","NASDAQ"],
  ["ATO","Atmos Energy Corporation","Utilities","Regulated Gas","NYSE"],
  ["DTW","DTE Energy Company 5.25 % Debentures 2017-01.12.77 Global","Utilities","Regulated Electric","NYSE"],
  ["MDLN","Medline Inc.","Healthcare","Medical - Instruments & Supplies","NASDAQ"],
  ["ON","ON Semiconductor Corporation","Technology","Semiconductors","NASDAQ"],
  ["VICI","VICI Properties Inc.","Real Estate","REIT - Diversified","NYSE"],
  ["ATI","ATI Inc.","Industrials","Manufacturing - Metal Fabrication","NYSE"],
  ["DG","Dollar General Corporation","Consumer Defensive","Discount Stores","NYSE"],
  ["FE","FirstEnergy Corp.","Utilities","Regulated Electric","NYSE"],
  ["CPAY","Corpay, Inc.","Technology","Software - Infrastructure","NYSE"],
  ["BSP","Bending Spoons S.p.A.","Technology","Software - Application","NASDAQ"],
  ["QSR","Restaurant Brands International Inc.","Consumer Cyclical","Restaurants","NYSE"],
  ["ZS","Zscaler, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["SYM","Symbotic Inc.","Industrials","Industrial - Machinery","NASDAQ"],
  ["CPNG","Coupang, Inc.","Consumer Cyclical","Specialty Retail","NYSE"],
  ["WSM","Williams-Sonoma, Inc.","Consumer Cyclical","Specialty Retail","NYSE"],
  ["CTSH","Cognizant Technology Solutions Corporation","Technology","Information Technology Services","NASDAQ"],
  ["VRSN","VeriSign, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["FISV","Fiserv, Inc.","Technology","Information Technology Services","NASDAQ"],
  ["WRB","W. R. Berkley Corporation","Financial Services","Insurance - Property & Casualty","NYSE"],
  ["RPRX","Royalty Pharma plc","Healthcare","Medical - Pharmaceuticals","NASDAQ"],
  ["CINF","Cincinnati Financial Corporation","Financial Services","Insurance - Property & Casualty","NASDAQ"],
  ["ES","Eversource Energy","Utilities","Regulated Electric","NYSE"],
  ["MTD","Mettler-Toledo International Inc.","Healthcare","Medical - Diagnostics & Research","NYSE"],
  ["OTIS","Otis Worldwide Corporation","Industrials","Industrial - Machinery","NYSE"],
  ["Q","Qnity Electronics, Inc.","Technology","Semiconductors","NYSE"],
  ["CNP","CenterPoint Energy, Inc.","Utilities","Regulated Electric","NYSE"],
  ["PPL","PPL Corporation","Utilities","Regulated Electric","NYSE"],
  ["RF","Regions Financial Corporation","Financial Services","Banks - Regional","NYSE"],
  ["DGX","Quest Diagnostics Incorporated","Healthcare","Medical - Diagnostics & Research","NYSE"],
  ["FOX","Fox Corporation","Communication Services","Entertainment","NASDAQ"],
  ["TPL","Texas Pacific Land Corporation","Energy","Oil & Gas Exploration & Production","NYSE"],
  ["DOV","Dover Corporation","Industrials","Industrial - Machinery","NYSE"],
  ["GFS","GLOBALFOUNDRIES Inc.","Technology","Semiconductors","NASDAQ"],
  ["LH","Labcorp Holdings Inc.","Healthcare","Medical - Diagnostics & Research","NYSE"],
  ["JBHT","J.B. Hunt Transport Services, Inc.","Industrials","Integrated Freight & Logistics","NASDAQ"],
  ["TCOM","Trip.com Group Limited","Consumer Cyclical","Travel Services","NASDAQ"],
  ["NVT","nVent Electric plc","Industrials","Electrical Equipment & Parts","NYSE"],
  ["INCY","Incyte Corporation","Healthcare","Biotechnology","NASDAQ"],
  ["XYL","Xylem Inc.","Industrials","Industrial - Machinery","NYSE"],
  ["STRD","Strategy Inc","Technology","Software - Application","NASDAQ"],
  ["EXPD","Expeditors International of Washington, Inc.","Industrials","Integrated Freight & Logistics","NYSE"],
  ["FCNCA","First Citizens BancShares, Inc.","Financial Services","Banks - Regional","NASDAQ"],
  ["PFG","Principal Financial Group, Inc.","Financial Services","Asset Management","NASDAQ"],
  ["SYF","Synchrony Financial","Financial Services","Financial - Credit Services","NYSE"],
  ["CIB","Grupo Cibest S.A.","Financial Services","Banks - Regional","NYSE"],
  ["ASTS","AST SpaceMobile, Inc.","Communication Services","Telecommunications Services","NASDAQ"],
  ["WST","West Pharmaceutical Services, Inc.","Healthcare","Medical - Instruments & Supplies","NYSE"],
  ["BNTX","BioNTech SE","Healthcare","Biotechnology","NASDAQ"],
  ["SMCI","Super Micro Computer, Inc.","Technology","Computer Hardware","NASDAQ"],
  ["CRCL","Circle Internet Group","Financial Services","Financial - Capital Markets","NYSE"],
  ["PHG","Koninklijke Philips N.V.","Healthcare","Medical - Devices","NYSE"],
  ["BG","Bunge Global S.A.","Consumer Defensive","Agricultural Farm Products","NYSE"],
  ["FWONK","Liberty Media Corporation","Communication Services","Entertainment","NASDAQ"],
  ["HUBB","Hubbell Incorporated","Industrials","Electrical Equipment & Parts","NYSE"],
  ["DRI","Darden Restaurants, Inc.","Consumer Cyclical","Restaurants","NYSE"],
  ["NRG","NRG Energy, Inc.","Utilities","Independent Power Producers","NYSE"],
  ["TSEM","Tower Semiconductor Ltd.","Technology","Semiconductors","NASDAQ"],
  ["KEY","KeyCorp","Financial Services","Banks - Regional","NYSE"],
  ["TPR","Tapestry, Inc.","Consumer Cyclical","Luxury Goods","NYSE"],
  ["PPG","PPG Industries, Inc.","Basic Materials","Chemicals - Specialty","NYSE"],
  ["KOF","Coca-Cola FEMSA, S.A.B. de C.V.","Consumer Defensive","Beverages - Non-Alcoholic","NYSE"],
  ["CASY","Casey's General Stores, Inc.","Consumer Cyclical","Specialty Retail","NASDAQ"],
  ["TROW","T. Rowe Price Group, Inc.","Financial Services","Asset Management","NASDAQ"],
  ["ULTA","Ulta Beauty, Inc.","Consumer Cyclical","Specialty Retail","NASDAQ"],
  ["SN","SharkNinja, Inc.","Consumer Cyclical","Furnishings, Fixtures & Appliances","NYSE"],
  ["VRSK","Verisk Analytics, Inc.","Technology","Software - Services","NASDAQ"],
  ["ROKU","Roku, Inc.","Communication Services","Entertainment","NASDAQ"],
  ["DLTR","Dollar Tree, Inc.","Consumer Defensive","Discount Stores","NASDAQ"],
  ["VLTO","Veralto Corporation","Industrials","Industrial - Pollution & Treatment Controls","NYSE"],
  ["AFRM","Affirm Holdings, Inc.","Financial Services","Financial - Credit Services","NASDAQ"],
  ["STRK","Strategy Inc","Technology","Software - Application","NASDAQ"],
  ["IHG","InterContinental Hotels Group PLC","Consumer Cyclical","Travel Lodging","NYSE"],
  ["FFIV","F5, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["PHM","PulteGroup, Inc.","Consumer Cyclical","Residential Construction","NYSE"],
  ["L","Loews Corporation","Financial Services","Insurance - Property & Casualty","NYSE"],
  ["EXE","Expand Energy Corporation","Energy","Oil & Gas Exploration & Production","NASDAQ"],
  ["AMRZ","Amrize Ltd","Basic Materials","Construction Materials","NYSE"],
  ["TCPA","TransCanada PipeLines Limited 6","Energy","Oil & Gas Midstream","NYSE"],
  ["CRS","Carpenter Technology Corporation","Basic Materials","Steel","NYSE"],
  ["FSLR","First Solar, Inc.","Energy","Solar","NASDAQ"],
  ["CHD","Church & Dwight Co., Inc.","Consumer Defensive","Household & Personal Products","NYSE"],
  ["BRO","Brown & Brown, Inc.","Financial Services","Insurance - Brokers","NYSE"],
  ["IOT","Samsara Inc.","Technology","Software - Infrastructure","NYSE"],
  ["AER","AerCap Holdings N.V.","Industrials","Rental & Leasing Services","NYSE"],
  ["SW","Smurfit Westrock plc","Consumer Cyclical","Packaging & Containers","NYSE"],
  ["SOFI","SoFi Technologies, Inc.","Financial Services","Financial - Credit Services","NASDAQ"],
  ["MKL","Markel Corporation","Financial Services","Insurance - Property & Casualty","NYSE"],
  ["GPN","Global Payments Inc.","Financial Services","Financial - Credit Services","NYSE"],
  ["YPF","YPF Sociedad Anónima","Energy","Oil & Gas Integrated","NYSE"],
  ["FCNCN","First Citizens BancShares, Inc. Depositary Shares, each representing a 1/40th interest in a share of 6.625% Non-Cumulative Perpetual Preferred Stock, Series E","Financial Services","Banks - Regional","NASDAQ"],
  ["EIX","Edison International","Utilities","Regulated Electric","NYSE"],
  ["TW","Tradeweb Markets Inc.","Financial Services","Financial - Capital Markets","NASDAQ"],
  ["FWONA","Formula One Group","Communication Services","Entertainment","NASDAQ"],
  ["OMC","Omnicom Group Inc.","Communication Services","Advertising Agencies","NYSE"],
  ["BCE","BCE Inc.","Communication Services","Telecommunications Services","NYSE"],
  ["RGLD","Royal Gold, Inc.","Basic Materials","Gold","NASDAQ"],
  ["IFF","International Flavors & Fragrances Inc.","Basic Materials","Chemicals - Specialty","NYSE"],
  ["DOW","Dow Inc.","Basic Materials","Chemicals","NYSE"],
  ["UTHR","United Therapeutics Corporation","Healthcare","Biotechnology","NASDAQ"],
  ["XPO","XPO Logistics, Inc.","Industrials","Trucking","NYSE"],
  ["PAAS","Pan American Silver Corp.","Basic Materials","Gold","NYSE"],
  ["GH","Guardant Health, Inc.","Healthcare","Medical - Diagnostics & Research","NASDAQ"],
  ["CMS","CMS Energy Corporation","Utilities","Regulated Electric","NYSE"],
  ["THC","Tenet Healthcare Corporation","Healthcare","Medical - Care Facilities","NYSE"],
  ["USFD","US Foods Holding Corp.","Consumer Defensive","Food Distribution","NYSE"],
  ["STZ","Constellation Brands, Inc.","Consumer Defensive","Beverages - Alcoholic","NYSE"],
  ["BCH","Banco de Chile","Financial Services","Banks - Regional","NYSE"],
  ["CDE","Coeur Mining, Inc.","Basic Materials","Gold","NYSE"],
  ["ENTG","Entegris, Inc.","Technology","Semiconductors","NASDAQ"],
  ["CMSA","CMS Energy Corporation 5.6% JRSUB NT 78","Utilities","Regulated Electric","NYSE"],
  ["MTSI","MACOM Technology Solutions Holdings, Inc.","Technology","Semiconductors","NASDAQ"],
  ["LYB","LyondellBasell Industries N.V.","Basic Materials","Chemicals - Specialty","NYSE"],
  ["CF","CF Industries Holdings, Inc.","Basic Materials","Agricultural Inputs","NYSE"],
  ["FICO","Fair Isaac Corporation","Technology","Software - Application","NYSE"],
  ["PKG","Packaging Corporation of America","Consumer Cyclical","Packaging & Containers","NYSE"],
  ["SQM","Sociedad Química y Minera de Chile S.A.","Basic Materials","Chemicals - Specialty","NYSE"],
  ["STE","STERIS plc","Healthcare","Medical - Specialties","NYSE"],
  ["CW","Curtiss-Wright Corporation","Industrials","Aerospace & Defense","NYSE"],
  ["RL","Ralph Lauren Corporation","Consumer Cyclical","Apparel - Manufacturers","NYSE"],
  ["SNX","TD Synnex Corp","Technology","Technology Distributors","NYSE"],
  ["RS","Reliance Steel & Aluminum Co.","Basic Materials","Steel","NYSE"],
  ["SOJD","Southern Company (The) Series 2","Utilities","Regulated Electric","NYSE"],
  ["WES","Western Midstream Partners, LP","Energy","Oil & Gas Midstream","NYSE"],
  ["FIS","Fidelity National Information Services, Inc.","Technology","Information Technology Services","NYSE"],
  ["AMCR","Amcor plc","Consumer Cyclical","Packaging & Containers","NYSE"],
  ["NI","NiSource Inc","Utilities","Regulated Gas","NYSE"],
  ["PR","Permian Resources Corporation","Energy","Oil & Gas Exploration & Production","NYSE"],
  ["ATHS","Athene Holding Ltd. 7.250% Fixe","Financial Services","Insurance - Life","NYSE"],
  ["WWD","Woodward, Inc.","Industrials","Aerospace & Defense","NASDAQ"],
  ["GMAB","Genmab A/S","Healthcare","Biotechnology","NASDAQ"],
  ["EFX","Equifax Inc.","Industrials","Consulting Services","NYSE"],
  ["RCI","Rogers Communications Inc.","Communication Services","Telecommunications Services","NYSE"],
  ["RIVN","Rivian Automotive, Inc.","Consumer Cyclical","Auto - Manufacturers","NASDAQ"],
  ["BR","Broadridge Financial Solutions, Inc.","Technology","Information Technology Services","NYSE"],
  ["SNA","Snap-on Incorporated","Industrials","Manufacturing - Tools & Accessories","NYSE"],
  ["LEN","Lennar Corporation","Consumer Cyclical","Residential Construction","NYSE"],
  ["SBAC","SBA Communications Corporation","Real Estate","REIT - Specialty","NASDAQ"],
  ["AQNB","Algonquin Power & Utilities Corp.","Utilities","Diversified Utilities","NYSE"],
  ["GIS","General Mills, Inc.","Consumer Defensive","Packaged Foods","NYSE"],
  ["DINO","HF Sinclair Corporation","Energy","Oil & Gas Refining & Marketing","NYSE"],
  ["VIV","Telefônica Brasil S.A.","Communication Services","Telecommunications Services","NYSE"],
  ["VTRS","Viatris Inc.","Healthcare","Drug Manufacturers - Specialty & Generic","NASDAQ"],
  ["SOJC","The Southern Company JR 2017B NT 77","Utilities","Regulated Electric","NYSE"],
  ["CHTR","Charter Communications, Inc.","Communication Services","Telecommunications Services","NASDAQ"],
  ["LUV","Southwest Airlines Co.","Industrials","Airlines, Airports & Air Services","NYSE"],
  ["EVRG","Evergy, Inc.","Utilities","Regulated Electric","NASDAQ"],
  ["MTZ","MasTec, Inc.","Industrials","Engineering & Construction","NYSE"],
  ["PKX","POSCO Holdings Inc.","Basic Materials","Steel","NYSE"],
  ["TSN","Tyson Foods, Inc.","Consumer Defensive","Agricultural Farm Products","NYSE"],
  ["BBY","Best Buy Co., Inc.","Consumer Cyclical","Specialty Retail","NYSE"],
  ["FDXF","FedEx Freight Holding Company, Inc.","Industrials","Integrated Freight & Logistics","NYSE"],
  ["TOST","Toast, Inc.","Technology","Software - Infrastructure","NYSE"],
  ["SSNC","SS&C Technologies Holdings, Inc.","Technology","Software - Application","NASDAQ"],
  ["GPC","Genuine Parts Company","Consumer Cyclical","Auto - Parts","NYSE"],
  ["FTAI","FTAI Aviation Ltd.","Industrials","Aerospace & Defense","NASDAQ"],
  ["KSPI","Joint Stock Company Kaspi.kz","Technology","Software - Infrastructure","NASDAQ"],
  ["BEKE","KE Holdings Inc.","Real Estate","Real Estate - Services","NYSE"],
  ["U","Unity Software Inc.","Technology","Software - Application","NYSE"],
  ["RBRK","Rubrik, Inc.","Technology","Software - Infrastructure","NYSE"],
  ["CDW","CDW Corporation","Technology","Information Technology Services","NASDAQ"],
  ["SBS","Companhia de Saneamento Básico do Estado de São Paulo - SABESP","Utilities","Regulated Water","NYSE"],
  ["IP","International Paper Company","Basic Materials","Paper, Lumber & Forest Products","NYSE"],
  ["PAA","Plains All American Pipeline, L.P.","Energy","Oil & Gas Midstream","NASDAQ"],
  ["WF","Woori Financial Group Inc.","Financial Services","Banks - Diversified","NYSE"],
  ["TPG","TPG Inc.","Financial Services","Asset Management","NASDAQ"],
  ["CHRW","C.H. Robinson Worldwide, Inc.","Industrials","Integrated Freight & Logistics","NASDAQ"],
  ["NWS","News Corporation","Communication Services","Publishing","NASDAQ"],
  ["GEN","Gen Digital Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["ZBH","Zimmer Biomet Holdings, Inc.","Healthcare","Medical - Devices","NYSE"],
  ["MGA","Magna International Inc.","Consumer Cyclical","Auto - Parts","NYSE"],
  ["EWBC","East West Bancorp, Inc.","Financial Services","Banks - Regional","NASDAQ"],
  ["OVV","Ovintiv Inc.","Energy","Oil & Gas Exploration & Production","NYSE"],
  ["MKSI","MKS Inc.","Technology","Hardware, Equipment & Parts","NASDAQ"],
  ["NTNX","Nutanix, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["TSCO","Tractor Supply Company","Consumer Cyclical","Specialty Retail","NASDAQ"],
  ["ITT","ITT Inc.","Industrials","Industrial - Machinery","NYSE"],
  ["BEN","Franklin Resources, Inc.","Financial Services","Asset Management","NYSE"],
  ["ESS","Essex Property Trust, Inc.","Real Estate","REIT - Residential","NYSE"],
  ["LNT","Alliant Energy Corporation","Utilities","Regulated Electric","NASDAQ"],
  ["DD","DuPont de Nemours, Inc.","Basic Materials","Chemicals","NYSE"],
  ["NDSN","Nordson Corporation","Industrials","Industrial - Machinery","NASDAQ"],
  ["FLUT","Flutter Entertainment plc","Consumer Cyclical","Gambling, Resorts & Casinos","NYSE"],
  ["CLH","Clean Harbors, Inc.","Industrials","Waste Management","NYSE"],
  ["BIP","Brookfield Infrastructure Partners L.P.","Utilities","Diversified Utilities","NYSE"],
  ["WCC","WESCO International, Inc.","Industrials","Industrial - Distribution","NYSE"],
  ["CNH","CNH Industrial N.V.","Industrials","Agricultural - Machinery","NYSE"],
  ["ROL","Rollins, Inc.","Industrials","Specialty Business Services","NYSE"],
  ["BSAC","Banco Santander-Chile","Financial Services","Banks - Regional","NYSE"],
  ["DUKB","Duke Energy Corporation 5.625%","Utilities","Regulated Electric","NYSE"],
  ["J","Jacobs Solutions Inc.","Industrials","Engineering & Construction","NYSE"],
  ["NLY","Annaly Capital Management, Inc.","Real Estate","REIT - Mortgage","NYSE"],
  ["WIT","Wipro Limited","Technology","Information Technology Services","NYSE"],
  ["ZTO","ZTO Express (Cayman) Inc.","Industrials","Integrated Freight & Logistics","NYSE"],
  ["NWSA","News Corporation","Communication Services","Publishing","NASDAQ"],
  ["FTV","Fortive Corporation","Technology","Hardware, Equipment & Parts","NYSE"],
  ["NVR","NVR, Inc.","Consumer Cyclical","Residential Construction","NYSE"],
  ["ZBRA","Zebra Technologies Corporation","Technology","Communication Equipment","NASDAQ"],
  ["INVH","Invitation Homes Inc.","Real Estate","REIT - Residential","NYSE"],
  ["JHX","James Hardie Industries plc","Basic Materials","Construction Materials","NYSE"],
  ["IEX","IDEX Corporation","Industrials","Industrial - Machinery","NYSE"],
  ["OWL","Blue Owl Capital Inc.","Financial Services","Asset Management","NYSE"],
  ["LDOS","Leidos Holdings, Inc.","Technology","Information Technology Services","NYSE"],
  ["MEDP","Medpace Holdings, Inc.","Healthcare","Medical - Diagnostics & Research","NASDAQ"],
  ["ASND","Ascendis Pharma A/S","Healthcare","Biotechnology","NASDAQ"],
  ["RGA","Reinsurance Group of America, Incorporated","Financial Services","Insurance - Reinsurance","NYSE"],
  ["TIGO","Millicom International Cellular S.A.","Communication Services","Telecommunications Services","NASDAQ"],
  ["APG","APi Group Corporation","Industrials","Engineering & Construction","NYSE"],
  ["VNOM","Viper Energy, Inc.","Energy","Oil & Gas Midstream","NASDAQ"],
  ["CCZ","Comcast Holdings Corp.","Communication Services","Telecommunications Services","NYSE"],
  ["BALL","Ball Corporation","Consumer Cyclical","Packaging & Containers","NYSE"],
  ["SITM","SiTime Corporation","Technology","Semiconductors","NASDAQ"],
  ["WY","Weyerhaeuser Company","Real Estate","REIT - Specialty","NYSE"],
  ["AS","Amer Sports, Inc.","Consumer Cyclical","Leisure","NYSE"],
  ["WPC","W. P. Carey Inc.","Real Estate","REIT - Diversified","NYSE"],
  ["FUTU","Futu Holdings Limited","Financial Services","Financial - Capital Markets","NASDAQ"],
  ["NBIX","Neurocrine Biosciences, Inc.","Healthcare","Biotechnology","NASDAQ"],
  ["JLL","Jones Lang LaSalle Incorporated","Real Estate","Real Estate - Services","NYSE"],
  ["APA","APA Corporation","Energy","Oil & Gas Exploration & Production","NASDAQ"],
  ["KIM","Kimco Realty Corporation","Real Estate","REIT - Retail","NYSE"],
  ["LSCC","Lattice Semiconductor Corporation","Technology","Semiconductors","NASDAQ"],
  ["AKAM","Akamai Technologies, Inc.","Technology","Software - Infrastructure","NASDAQ"],
  ["IREN","IREN Limited","Technology","Information Technology Services","NASDAQ"],
  ["RZC","Reinsurance Group of America, Incorporated","Financial Services","Insurance - Reinsurance","NYSE"],
  ["CG","The Carlyle Group Inc.","Financial Services","Asset Management","NASDAQ"],
  ["CX","CEMEX, S.A.B. de C.V.","Basic Materials","Construction Materials","NYSE"],
  ["DOCN","DigitalOcean Holdings, Inc.","Technology","Software - Infrastructure","NYSE"],
  ["H","Hyatt Hotels Corporation","Consumer Cyclical","Travel Lodging","NYSE"],
  ["STLA","Stellantis N.V.","Consumer Cyclical","Auto - Manufacturers","NYSE"],
  ["KEP","Korea Electric Power Corporation","Utilities","Regulated Electric","NYSE"],
  ["CRBG","Corebridge Financial, Inc.","Financial Services","Asset Management","NYSE"],
  ["SOLV","Solventum Corporation","Healthcare","Medical - Instruments & Supplies","NYSE"],
  ["HST","Host Hotels & Resorts, Inc.","Real Estate","REIT - Hotel & Motel","NASDAQ"],
  ["EMA","Emera Incorporated","Utilities","Regulated Electric","NYSE"],
  ["RBC","RBC Bearings Incorporated","Industrials","Manufacturing - Tools & Accessories","NYSE"],
  ["JAZZ","Jazz Pharmaceuticals plc","Healthcare","Biotechnology","NASDAQ"],
  ["RBA","RB Global, Inc.","Industrials","Specialty Business Services","NYSE"],
  ["LAMR","Lamar Advertising Company","Real Estate","REIT - Specialty","NASDAQ"],
  ["DT","Dynatrace, Inc.","Technology","Software - Application","NYSE"],
  ["BURL","Burlington Stores, Inc.","Consumer Cyclical","Apparel - Retail","NYSE"],
  ["AGI","Alamos Gold Inc.","Basic Materials","Gold","NYSE"],
  ["PNFP","Pinnacle Financial Partners, Inc.","Financial Services","Banks - Regional","NYSE"],
  ["UNM","Unum Group","Financial Services","Insurance - Life","NYSE"],
  ["ARMK","Aramark","Industrials","Specialty Business Services","NYSE"],
  ["STRL","Sterling Infrastructure, Inc.","Industrials","Engineering & Construction","NASDAQ"],
  ["PTC","PTC Inc.","Technology","Software - Application","NASDAQ"],
  ["COKE","Coca-Cola Consolidated, Inc.","Consumer Defensive","Beverages - Non-Alcoholic","NASDAQ"],
  ["SMTC","Semtech Corporation","Technology","Semiconductors","NASDAQ"],
  ["PFGC","Performance Food Group Co","Consumer Defensive","Food Distribution","NYSE"],
  ["TLK","Perusahaan Perseroan (Persero) PT Telekomunikasi Indonesia Tbk","Communication Services","Telecommunications Services","NYSE"],
  ["YUMC","Yum China Holdings, Inc.","Consumer Cyclical","Restaurants","NYSE"],
  ["GIB","CGI Inc.","Technology","Information Technology Services","NYSE"],
  ["TRU","TransUnion","Financial Services","Financial - Data & Stock Exchanges","NYSE"],
  ["PS","Pershing Square Inc.","Financial Services","Asset Management","NYSE"],
  ["INIO","INNIO N.V. Ordinary Shares","Industrials","Industrial - Machinery","NASDAQ"],
  ["EG","Everest Group, Ltd.","Financial Services","Insurance - Reinsurance","NYSE"],
  ["LTM","LATAM Airlines Group S.A.","Industrials","Airlines, Airports & Air Services","NYSE"],
  ["ECHO","EchoStar Corporation","Communication Services","Telecommunications Services","NASDAQ"],
  ["GFL","GFL Environmental Inc.","Industrials","Waste Management","NYSE"],
  ["WMG","Warner Music Group Corp.","Communication Services","Entertainment","NASDAQ"],
  ["MAA","Mid-America Apartment Communities, Inc.","Real Estate","REIT - Residential","NYSE"],
  ["FN","Fabrinet","Technology","Hardware, Equipment & Parts","NYSE"],
  ["EXEL","Exelixis, Inc.","Healthcare","Biotechnology","NASDAQ"],
  ["UNMA","Unum Group 6.250% JR NT58","Financial Services","Insurance - Life","NYSE"],
  ["ALB","Albemarle Corporation","Basic Materials","Chemicals - Specialty","NYSE"],
  ["EQH","Equitable Holdings, Inc.","Financial Services","Asset Management","NYSE"],
  ["LOGI","Logitech International S.A.","Technology","Computer Hardware","NASDAQ"],
  ["ULS","UL Solutions Inc.","Industrials","Specialty Business Services","NYSE"],
  ["PAG","Penske Automotive Group, Inc.","Consumer Cyclical","Auto - Dealerships","NYSE"],
  ["SKM","SK Telecom Co.,Ltd","Communication Services","Telecommunications Services","NYSE"],
  ["TKO","TKO Group Holdings, Inc.","Communication Services","Entertainment","NYSE"],
  ["BBIO","BridgeBio Pharma, Inc.","Healthcare","Biotechnology","NASDAQ"],
  ["TU","Telus Corp","Communication Services","Telecommunications Services","NYSE"],
  ["SUI","Sun Communities, Inc.","Real Estate","REIT - Residential","NYSE"],
  ["IVZ","Invesco Ltd.","Financial Services","Asset Management","NYSE"],
  ["TLN","Talen Energy Corporation","Utilities","Independent Power Producers","NASDAQ"],
  ["ARCC","Ares Capital Corporation","Financial Services","Asset Management","NASDAQ"],
  ["DOC","Healthpeak Properties, Inc.","Real Estate","REIT - Healthcare Facilities","NYSE"],
  ["OHI","Omega Healthcare Investors, Inc.","Real Estate","REIT - Healthcare Facilities","NYSE"],
  ["KKRS","KKR Group Finance Co. IX LLC 4.","Financial Services","Financial - Credit Services","NYSE"],
  ["AIZN","Assurant, Inc. 5.25% Subordinat","Financial Services","Insurance - Property & Casualty","NYSE"],
  ["BWXT","BWX Technologies, Inc.","Industrials","Aerospace & Defense","NYSE"],
  ["AEFC","Aegon Funding Company LLC","Financial Services","Insurance - Diversified","NYSE"],
  ["AIZ","Assurant, Inc.","Financial Services","Insurance - Property & Casualty","NYSE"],
  ["SGI","Somnigroup International Inc","Consumer Cyclical","Furnishings, Fixtures & Appliances","NYSE"],
  ["CACI","CACI International Inc","Technology","Information Technology Services","NYSE"],
  ["BMNR","Bitmine Immersion Technologies, Inc.","Financial Services","Financial - Capital Markets","NYSE"],
  ["REG","Regency Centers Corporation","Real Estate","REIT - Retail","NASDAQ"],
  ["IONQ","IonQ, Inc.","Technology","Computer Hardware","NYSE"],
  ["TYL","Tyler Technologies, Inc.","Technology","Software - Application","NYSE"],
  ["MKC","McCormick & Company, Incorporated","Consumer Defensive","Packaged Foods","NYSE"],
  ["EMBJ","Embraer S.A.","Industrials","Aerospace & Defense","NYSE"],
  ["LECO","Lincoln Electric Holdings, Inc.","Industrials","Manufacturing - Tools & Accessories","NASDAQ"],
  ["TXT","Textron Inc.","Industrials","Aerospace & Defense","NYSE"],
  ["AEG","Aegon Ltd.","Financial Services","Insurance - Diversified","NYSE"],
  ["RNR","RenaissanceRe Holdings Ltd.","Financial Services","Insurance - Reinsurance","NYSE"],
  ["SMMT","Summit Therapeutics Inc.","Healthcare","Biotechnology","NASDAQ"],
  ["RVTY","Revvity, Inc.","Healthcare","Medical - Diagnostics & Research","NYSE"],
  ["SWK","Stanley Black & Decker, Inc.","Industrials","Manufacturing - Tools & Accessories","NYSE"],
  ["BWA","BorgWarner Inc.","Consumer Cyclical","Auto - Parts","NYSE"],
  ["HL","Hecla Mining Company","Basic Materials","Other Precious Metals","NYSE"],
  ["ONTO","Onto Innovation Inc.","Technology","Semiconductors","NYSE"],
  ["XELLL","Xcel Energy Inc. 6.25% Junior Subordinated Notes, Series due 2085","Utilities","Regulated Electric","NASDAQ"],
  ["W","Wayfair Inc.","Consumer Cyclical","Specialty Retail","NYSE"],
  ["CSL","Carlisle Companies Incorporated","Basic Materials","Construction Materials","NYSE"],
  ["FIVE","Five Below, Inc.","Consumer Cyclical","Specialty Retail","NASDAQ"],
  ["MAS","Masco Corporation","Basic Materials","Construction Materials","NYSE"],
  ["CHKP","Check Point Software Technologies Ltd.","Technology","Software - Infrastructure","NASDAQ"],
] as const;
