"use client";

import { useRouter } from "next/navigation";

export default function DiscussionForums() {
  const router = useRouter();

  const categories = [
    {
      title: "📈 Stock Market Discussions",
      description:
        "Talk about daily market movements, share stock ideas, and analyze earnings reports in real time.",
      color: "bg-blue-50",
      link: "/community/forums/stocks",
    },
    {
      title: "💰 Investing Strategies",
      description:
        "Discuss portfolio building, long-term wealth strategies, and risk management methods used by professionals.",
      color: "bg-yellow-50",
      link: "/community/forums/strategies",
    },
    {
      title: "🤖 AI Forecasts & Analysis",
      description:
        "Share insights and forecasts generated by AI models. Compare human vs machine predictions for major assets.",
      color: "bg-purple-50",
      link: "/community/forums/ai-forecasts",
    },
    {
      title: "🏠 Real Estate Investing",
      description:
        "Explore real estate market trends, REITs, and property management tips from investors around the world.",
      color: "bg-green-50",
      link: "/community/forums/real-estate",
    },
    {
      title: "💬 Off-Topic Lounge",
      description:
        "Relax and chat about anything — from macroeconomics to personal finance or even the latest finance memes.",
      color: "bg-gray-50",
      link: "/community/forums/lounge",
    },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 to-gray-100">
      {/* Header */}
      <header className="bg-white shadow-sm py-5">
        <div className="max-w-7xl mx-auto flex justify-between items-center px-6">
          <h1
            onClick={() => router.push("/dashboard")}
            className="text-2xl font-semibold text-gray-900 cursor-pointer"
          >
            💬 WallStreetStocks Forums
          </h1>
          <button
            onClick={() => router.push("/dashboard/community")}
            className="bg-yellow-400 hover:bg-yellow-500 text-black px-5 py-2 rounded-full font-medium transition-all"
          >
            ← Back to Community
          </button>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto px-6 py-14 text-center">
        <h2 className="text-4xl font-bold mb-4 text-gray-900">
          Discussion Forums
        </h2>
        <p className="text-gray-600 mb-12 max-w-2xl mx-auto">
          Dive into focused discussions led by investors and analysts. 
          Join conversations about stocks, strategies, AI forecasts, and more.
        </p>

        {/* Forum Categories */}
        <section className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {categories.map((cat) => (
            <div
              key={cat.title}
              className={`${cat.color} rounded-2xl shadow-sm hover:shadow-md transition-all p-6 text-left cursor-pointer border border-gray-100`}
              onClick={() => router.push(cat.link)}
            >
              <h3 className="text-xl font-semibold mb-2">{cat.title}</h3>
              <p className="text-gray-600 mb-4">{cat.description}</p>
              <button className="text-yellow-600 font-semibold hover:underline">
                Enter Forum →
              </button>
            </div>
          ))}
        </section>

        {/* CTA */}
        <div className="mt-16 text-center">
          <button
            onClick={() => router.push("/community")}
            className="bg-yellow-400 hover:bg-yellow-500 text-black font-semibold py-3 px-10 rounded-full transition-all"
          >
            Back to Community Hub
          </button>
        </div>
      </main>
    </div>
  );
}
